definitions:
  api.AssetPrice_Strike_Positions:
    description: Contains strike and expiry prices for a given asset price
    properties:
      assetPrice:
        description: Asset price
        type: number
      strikePositions:
        description: Option price/dtes per strike
        items:
          $ref: '#/definitions/api.Strike_Positions'
        type: array
    type: object
  api.OptionChainResponse:
    description: The response object for the CalculateOptionChain endpoint
    properties:
      assetName:
        description: Name of the asset
        type: string
      optionChain:
        description: Option price/dtes per asset price / strike
        items:
          $ref: '#/definitions/api.AssetPrice_Strike_Positions'
        type: array
    type: object
  api.Position:
    description: Contains the call and put prices for a specific number of days to
      expiry
    properties:
      daysToExpiry:
        description: Days to expiry
        type: number
      price:
        description: Option price
        type: number
    type: object
  api.Strike_Positions:
    description: Contains option prices for different expiry dates at a given strike
      price
    properties:
      positions:
        description: Option prices per expiry date
        items:
          $ref: '#/definitions/api.Position'
        type: array
      strikePrice:
        description: Strike price
        type: number
    type: object
info:
  contact: {}
paths:
  /optionChain:
    get:
      consumes:
      - application/json
      description: Calculates option prices for a range of asset prices, strike prices,
        and days to expiry.
      parameters:
      - description: Name of asset
        in: query
        name: assetName
        required: true
        type: string
      - description: Type of option (Call, Put)
        in: query
        name: optionType
        required: true
        type: string
      - description: Low end of asset price range
        in: query
        name: assetPriceLow
        required: true
        type: number
      - description: High end of asset price range
        in: query
        name: assetPriceHigh
        required: true
        type: number
      - description: Step amount for asset price range (default = 1.0)
        in: query
        name: assetPriceStep
        type: number
      - description: Low end of strike price range
        in: query
        name: strikePriceLow
        required: true
        type: number
      - description: High end of strike price range
        in: query
        name: strikePriceHigh
        required: true
        type: number
      - description: Step amount for strike price range (default = 1.0)
        in: query
        name: strikePriceStep
        type: number
      - description: Low end of days to expiry range
        in: query
        name: daysToExpiryLow
        required: true
        type: number
      - description: High end of days to expiry range
        in: query
        name: daysToExpiryHigh
        required: true
        type: number
      - description: Step amount for days to expiry range (default = 1.0)
        in: query
        name: daysToExpiryStep
        type: number
      - description: Risk-free interest rate
        in: query
        name: riskFreeRate
        required: true
        type: number
      - description: Volatility of the asset
        in: query
        name: volatility
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OptionChainResponse'
      summary: Calculate option chain
      tags:
      - options
swagger: "2.0"
