// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/optionChain": {
            "get": {
                "description": "Calculates option prices for a range of asset prices, strike prices, and days to expiry.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "options"
                ],
                "summary": "Calculate option chain",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of asset",
                        "name": "assetName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Low end of asset price range",
                        "name": "assetPriceLow",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "High end of asset price range",
                        "name": "assetPriceHigh",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Low end of strike price range",
                        "name": "strikePriceLow",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "High end of strike price range",
                        "name": "strikePriceHigh",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Risk-free interest rate",
                        "name": "riskFreeRate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Volatility of the asset",
                        "name": "volatility",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Days to expiry of the option",
                        "name": "daysToExpiry",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.OptionChainResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.AssetStrikeExpiryPrice": {
            "description": "Contains strike and expiry prices for a given asset price",
            "type": "object",
            "properties": {
                "assetPrice": {
                    "description": "Asset price",
                    "type": "number"
                },
                "strikeExpiryPrices": {
                    "description": "Prices per strike and expiry",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.StrikeExpiryPrice"
                    }
                }
            }
        },
        "main.ExpiryPrice": {
            "description": "Contains the call and put prices for a specific number of days to expiry",
            "type": "object",
            "properties": {
                "callPrice": {
                    "description": "Call option price",
                    "type": "number"
                },
                "daysToExpiry": {
                    "description": "Days to expiry",
                    "type": "number"
                },
                "putPrice": {
                    "description": "Put option price",
                    "type": "number"
                }
            }
        },
        "main.OptionChainResponse": {
            "description": "The response object for the CalculateOptionChain endpoint",
            "type": "object",
            "properties": {
                "assetName": {
                    "description": "Name of the asset",
                    "type": "string"
                },
                "assetStrikeExpiryPrices": {
                    "description": "Option prices per asset price and strike price",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.AssetStrikeExpiryPrice"
                    }
                }
            }
        },
        "main.StrikeExpiryPrice": {
            "description": "Contains call and put prices for different expiry dates at a given strike price",
            "type": "object",
            "properties": {
                "expiryPrices": {
                    "description": "Call and put prices per expiry date",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.ExpiryPrice"
                    }
                },
                "strikePrice": {
                    "description": "Strike price",
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
